name: ladder
description: "An app for tracking data for showdown ladder nights"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  backstreets_widgets: ^0.36.0
  cupertino_icons: ^1.0.8
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  json_annotation: ^4.9.0
  mailer: ^6.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.0-dev.17
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.0
  custom_lint: ^0.8.0
  drift_dev: ^2.28.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  uses-material-design: true
